// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FinalsTrack.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace FinalsTrack.Api.Data;

public partial class FinalsTrackDbContext : DbContext
{
    public FinalsTrackDbContext(DbContextOptions<FinalsTrackDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<ExamSeason> ExamSeasons { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<StressLog> StressLogs { get; set; }

    public virtual DbSet<StudyBlock> StudyBlocks { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Exams__3214EC07CDD3F796");

            entity.HasIndex(e => e.ExamSeasonId, "IDX_Exams_Season");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.ExamSeason).WithMany(p => p.Exams)
                .HasForeignKey(d => d.ExamSeasonId)
                .HasConstraintName("FK__Exams__ExamSeaso__49C3F6B7");

            entity.HasOne(d => d.Subject).WithMany(p => p.Exams)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Exams__SubjectId__4AB81AF0");
        });

        modelBuilder.Entity<ExamSeason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ExamSeas__3214EC07A318C3E4");

            entity.HasIndex(e => e.UserId, "IDX_ExamSeasons_User");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.ExamSeasons)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ExamSeaso__UserI__4316F928");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3214EC0788EB1325");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefreshTokens_CreatedAt");
            entity.Property(e => e.IsRevoked).HasDefaultValue(false);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__RefreshTo__UserI__59063A47");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC07B8AB8348");

            entity.HasIndex(e => e.Name, "UQ__Roles__737584F63A582242").IsUnique();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<StressLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StressLo__3214EC07BE08B5BE");

            entity.HasIndex(e => e.ExamId, "IDX_StressLogs_Exam");

            entity.Property(e => e.LoggedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Exam).WithMany(p => p.StressLogs)
                .HasForeignKey(d => d.ExamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StressLog__ExamI__5441852A");

            entity.HasOne(d => d.User).WithMany(p => p.StressLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StressLog__UserI__5535A963");
        });

        modelBuilder.Entity<StudyBlock>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StudyBlo__3214EC07F0CC88E0");

            entity.HasIndex(e => e.ExamId, "IDX_StudyBlocks_Exam");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Exam).WithMany(p => p.StudyBlocks)
                .HasForeignKey(d => d.ExamId)
                .HasConstraintName("FK__StudyBloc__ExamI__4F7CD00D");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subjects__3214EC07B6108F0C");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.Subjects)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Subjects__UserId__45F365D3");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC071F444FBE");

            entity.HasIndex(e => e.Email, "IDX_Users_Email");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D105348E9B9A44").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId }).HasName("PK__UserRole__AF2760AD82040C99");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__UserRoles__RoleI__3F466844");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserRoles__UserI__3E52440B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}